services:
  pbl_app:
    build:
      args:
        user: pbl_user
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: pbl_app
    container_name: pbl_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - pbl_network

  pbl_nginx:
    image: nginx:alpine
    container_name: pbl_nginx
    restart: unless-stopped
    ports:
      - "8022:80"
    volumes:
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      - pbl_network

  pbl_db:
    image: mysql:8.0
    container_name: pbl_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pbl
    ports:
      - "3307:3306"
    networks:
      - pbl_network

networks:
  pbl_network:
    name: pbl_network
    driver: bridge